import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../../../packages/core/package.json', import.meta.url));
const ts = require('typescript');
const source = readFileSync(new URL('../../../packages/core/src/operations/sentry-policy.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2022 } }).outputText;
const { createSentryPolicy } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
let time = 1_000_000;
const event = { level: 'error', environment: 'production', message: 'SECRET', user: { email: 'SECRET' }, request: { headers: { Authorization: 'SECRET' } }, exception: { values: [{ value: 'SECRET' }] }, tags: { component: 'api', diagnostic: 'JOB_FAILED', token: 'SECRET' } };
assert.equal(createSentryPolicy()(event), null, 'disabled by default');
const policy = createSentryPolicy({ enabled: true, now: () => time });
assert.equal(policy({ ...event, environment: 'local' }), null);
assert.equal(policy({ ...event, level: 'warning' }), null);
const safe = policy(event);
assert.equal(safe.message, 'JOB_FAILED');
assert.ok(!JSON.stringify(safe).includes('SECRET'));
assert.equal(policy(event), null, 'same issue suppressed');
time += 300_000;
assert.ok(policy(event), 'issue allowed after 5 minutes');
assert.equal(policy(event), null);
console.log('Sentry policy: disabled default, environment/level filters, secret projection, dedupe/expiry passed');

const rate = createSentryPolicy({ enabled: true, now: () => time });
for (const component of ['web', 'api', 'operations']) assert.ok(rate({ ...event, tags: { component, diagnostic: 'JOB_FAILED' } }));
assert.equal(rate({ ...event, tags: { component: 'api', diagnostic: 'UNEXPECTED_ERROR' } }), null, 'three per minute budget');
time += 60_000;
assert.ok(rate({ ...event, tags: { component: 'api', diagnostic: 'UNEXPECTED_ERROR' } }), 'budget resets');
console.log('Sentry local rate limit: 3 per minute and reset passed');
