// Generated from globals.css by .kiro/specs/admin-design/generate-schema.py.
export const DESIGN_SCHEMA = [
  {
    key: "--color-brand-50",
    defaultValue: "#eff4ff",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-100",
    defaultValue: "#dbe6fe",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-200",
    defaultValue: "#bfcffe",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-300",
    defaultValue: "#93aefb",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-400",
    defaultValue: "#6082f7",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-500",
    defaultValue: "#3b5cf2",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-600",
    defaultValue: "#1d4ed8",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-700",
    defaultValue: "#1a3fc0",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-800",
    defaultValue: "#1b359c",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-900",
    defaultValue: "#1c2f7c",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-brand-950",
    defaultValue: "#131e4f",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-accent-400",
    defaultValue: "#facc15",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-accent-500",
    defaultValue: "#eab308",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-surface-raised",
    defaultValue: "#fcfbf8",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--color-text-secondary",
    defaultValue: "#5b524b",
    kind: "color",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--radius-sm",
    defaultValue: "4px",
    kind: "length",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--radius-md",
    defaultValue: "8px",
    kind: "length",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--radius-lg",
    defaultValue: "10px",
    kind: "length",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--radius-xl",
    defaultValue: "14px",
    kind: "length",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--radius-2xl",
    defaultValue: "18px",
    kind: "length",
    min: 0,
    max: 24,
    unit: "px",
  },
  {
    key: "--space-section",
    defaultValue: "5rem",
    kind: "length",
    min: 0,
    max: 8,
    unit: "rem",
  },
  {
    key: "--space-card",
    defaultValue: "1.25rem",
    kind: "length",
    min: 0,
    max: 8,
    unit: "rem",
  },
  {
    key: "--design-font-size",
    defaultValue: "16px",
    kind: "length",
    min: 14,
    max: 20,
    unit: "px",
  },
] as const;
